num_envs: 20
epochs: 100
eval_frequence: 20
encoder_layers:
  - 256
  - 256
  - 256
  - 256
actor_layers:
  - 256
  - 256
value_layers:
  - 256
  - 256
critic_layers:
  - 256
  - 256
learning_rate: 3.0e-4
update_iteration: 100
batch_size: 1000
gamma: 0.98
tau: 0.005
expectile: 0.7
beta: 3
replay_path: "replays"