num_envs: 20
max_steps: 100
epochs: 100
eval_frequence: 20
encoder_layers:
  - 256
  - 256
  - 256
  - 256
actor_layers:
  - 256
  - 256
value_layers:
  - 256
  - 256
learning_rate: 3.0e-4
update_iteration: 25
batch_size: 1000
gamma: 0.95
lambda_: 0.95
value_loss_weight: 0.5
entropy_weight: 0.01
max_grad_norm: 0.5
clip_ratio: 0.2
regularization_weight: 0.0